import logo1 from '../Assets/images/khazzilogo.png';
import logo2 from '../Assets/images/Khazzidev.png';
import logo3 from '../Assets/images/logo-s.png';

const database = [
  {
    id: 1,
    image: logo1,
    time: "1hr",
    title: "Electrician",
    location: "Ibadan",
    desc: "Install, maintain, and repair electrical systems.",
    company: "Bright Sparks Ltd.",
  },
  {
    id: 2,
    image: logo2,
    time: "now",
    title: "Plumber",
    location: "Kaduna",
    desc: "Install and repair water supply and drainage systems.",
    company: "Flow Masters",
  },
  {
    id: 3,
    image: logo3,
    time: "12hr",
    title: "Carpenter",
    location: "Abeokuta",
    desc: "Construct, install, and repair wooden structures and furniture.",
    company: "WoodWorks Nigeria",
  },
  {
    id: 4,
    image: logo1,
    time: "2hr",
    title: "Welder",
    location: "Enugu",
    desc: "Join metal parts using welding equipment.",
    company: "MetalFusion Inc.",
  },
  {
    id: 5,
    image: logo2,
    time: "5hr",
    title: "Bricklayer",
    location: "Benin City",
    desc: "Build and repair walls, chimneys, and other structures using bricks and mortar.",
    company: "BrickStrong Construction",
  },
  {
    id: 6,
    image: logo3,
    time: "8hr",
    title: "Mechanic",
    location: "Port Harcourt",
    desc: "Inspect, maintain, and repair vehicles and machinery.",
    company: "AutoFix Nigeria",
  },
  {
    id: 7,
    image: logo1,
    time: "3hr",
    title: "Painter",
    location: "Calabar",
    desc: "Prepare surfaces and apply paint or other finishes.",
    company: "ColorSplash Services",
  },
  {
    id: 8,
    image: logo2,
    time: "4hr",
    title: "Tailor",
    location: "Aba",
    desc: "Design, make, alter, and repair clothing.",
    company: "Fashion Hub",
  },
  {
    id: 9,
    image: logo3,
    time: "9hr",
    title: "Mason",
    location: "Kano",
    desc: "Lay stone, brick, and concrete blocks to construct structures.",
    company: "Solid Foundations Ltd.",
  },
  {
    id: 10,
    image: logo1,
    time: "6hr",
    title: "Driver",
    location: "Jos",
    desc: "Transport goods or people safely to their destinations.",
    company: "QuickTransit Services",
  },
  {
    id: 11,
    image: logo2,
    time: "7hr",
    title: "Housekeeper",
    location: "Osogbo",
    desc: "Maintain cleanliness and order in homes or commercial establishments.",
    company: "Clean & Tidy Co.",
  },
  {
    id: 12,
    image: logo3,
    time: "10hr",
    title: "Gardener",
    location: "Uyo",
    desc: "Cultivate and maintain gardens and landscapes.",
    company: "GreenThumb Landscaping",
  },
];

export default database;
